# thaw_script_config.ini
#
# Copyright (C) 2015-2024 Vas Vasiliadis
# University of Chicago
#
# Results thaw utility configuration
# For use with thaw_script.py
# ** Remember to first read config from util_config.ini for default values
#
##

# AWS SNS Settings
[sns]

[sqs]
ThawQueueUrl = https://sqs.us-east-1.amazonaws.com/127134666975/nalinprabhath_a16_thaw_requests
WaitTime = 20
MaxMessages = 5

[dynamodb]
AnnotationsTable = nalinprabhath_annotations

[glacier]
VaultName = ucmpcs

### EOF
