# notify_config.ini
#
# Copyright (C) 2015-2024 Vas Vasiliadis
# University of Chicago
#
# Results notification utility configuration for use with notify.py
# ** Remember to first read config from util_config.ini for default values
#
##

# GAS parameters
[gas]

[aws]
AwsRegionName = us-east-1

# AWS SQS Settings
[sqs]
ResultsQueueUrl = https://sqs.us-east-1.amazonaws.com/127134666975/nalinprabhath_a17_job_results
WaitTime = 20
MaxMessages = 10

[scheduler]
ArchiveQueueArn = arn:aws:sqs:us-east-1:127134666975:nalinprabhath_a14_archive_requests
SchedulerRoleArn = arn:aws:iam::127134666975:role/service_role_nalinprabhath
ScheduleGroup = default

[app]
Sender = nalinprabhath@ucmpcs.org
BaseUrl = https://nalinprabhath-a16-web.ucmpcs.org:4433

### EOF
