# annotator_config.ini
#
# Copyright (C) 2015-2023 Vas Vasiliadis
# University of Chicago
#
# GAS annotator configuration
#
##

[DEFAULT]
CnetId = nalinprabhath

# GAS parameters
[gas]
AnnotationsTable = ${CnetId}_annotations

# AnnTools settings
[ann]

# AWS general settings
[aws]
AwsRegionName = us-east-1

# AWS S3 settings
[s3]
InputsBucketName = gas-inputs
ResultsBucketName = gas-results
KeyPrefix = ${CnetId}/

[DynamoDb]
AnnotationsTable = ${CnetId}_annotations

# AWS SNS settings
[sns]
JobResultsTopicArn = arn:aws:sns:us-east-1:127134666975:nalinprabhath_a17_job_results

# AWS SQS Settings
[sqs]
SqsQueueUrl = https://sqs.us-east-1.amazonaws.com/127134666975/nalinprabhath_a17_job_requests
WaitTime = 20
MaxMessages = 10

[app]
Username = userX
JobsDir = anntools/jobs
DataDir = anntools/data
AnnToolsDir = anntools

### EOF
