# archive_script_config.ini
#
# Copyright (C) 2015-2024 Vas Vasiliadis
# University of Chicago
#
# Results notification utility configuration for use with archive_script.py
# ** Remember to first read config from util_config.ini for default values
#
##

# archive_script_config.ini

[aws]
AwsRegionName = us-east-1

[sqs]
ArchiveQueueUrl = https://sqs.us-east-1.amazonaws.com/127134666975/nalinprabhath_a14_archive_requests
WaitTime = 20
MaxMessages = 5

[dynamodb]
AnnotationsTable = nalinprabhath_annotations

[s3]
ResultsBucketName = gas-results

[glacier]
VaultName = ucmpcs

### EOF
